### ISSUE TITLE
Allow the use of `numpy>=2.0` with Arelle

### ISSUE THREAD

**Issue by zaneselvans** [Arelle/Arelle#1325]
### What should we change and why?

[Numpy 2.0](https://github.com/numpy/numpy/releases/tag/v2.0.0) has been out for a couple of months, and Numpy 2.1.0 was just released. However Numpy is pinned to 1.* in Arelle's `pyproject.toml`:

```toml
dependencies = [
    'certifi',
    'filelock',
    'isodate==0.*',
    'lxml>=4,<6',
    'numpy==1.*',
    'openpyxl==3.*',
    'pyparsing==3.*',
    'python-dateutil==2.*',
    'regex',
]
```

Are there plans to allow the upgrade? Will it be complex? Arelle and MLFlow are the last of our dependencies to have this restriction, and someone just opened [an MLFlow issue](https://github.com/mlflow/mlflow/issues/12967) about it.

Thank you!
