### ISSUE TITLE
Configure dependabot to update python dependencies

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#254]
Dependabot should be configured to manage python dependency updates. With `RDFLib >= 6` included in the ignore list.

**Comment by ggravlingen** [comment]
I looked into a possible dependabot-config over the weekend that I believed would be in line with our discussions in the dependency-pin PR. The idea was to not touch any of the lib's core dependencies and only add dev dependencies. Are you willing to go further than the suggestion below and include only include `RDFLib` in an ignore-list?

```
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "mock"
      - dependency-name: "mypy"
      - dependency-name: "types-PyMySQL"
      - dependency-name: "types-pytz"
      - dependency-name: "types-simplejson"
      - dependency-name: "types-ujson"
      - dependency-name: "types-waitress"
      - dependency-name: "pytest"

```
