### ISSUE TITLE
Upload release triggered build artifacts to release

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#438]
### What should we change and why?

For the Linux, macOS, Windows, and Python package workflows, and a step to [upload build artifacts to the release](https://github.com/softprops/action-gh-release) if the current event is coming from a tag:
```
- name: Upload release artifact
  uses: softprops/action-gh-release@v0.1.14
  if: startsWith(github.ref, 'refs/tags/')
  with:
    files: <file-glob-pattern>
```
